const mongoose = require("mongoose");

const payrollSchema = new mongoose.Schema({
  employee: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Employee',
    required: true
  },
  
  // Pay Period
  month: {
    type: Number,
    required: true,
    min: 1,
    max: 12
  },
  year: {
    type: Number,
    required: true
  },

  // Earnings
  earnings: {
    basic: { type: Number, default: 0 },
    hra: { type: Number, default: 0 }, // House Rent Allowance
    conveyance: { type: Number, default: 0 },
    medical: { type: Number, default: 0 },
    specialAllowance: { type: Number, default: 0 },
    bonus: { type: Number, default: 0 },
    overtime: { type: Number, default: 0 },
    other: { type: Number, default: 0 }
  },

  // Deductions
  deductions: {
    providentFund: { type: Number, default: 0 },
    professionalTax: { type: Number, default: 0 },
    incomeTax: { type: Number, default: 0 },
    insurance: { type: Number, default: 0 },
    loanRepayment: { type: Number, default: 0 },
    other: { type: Number, default: 0 }
  },

  // Attendance summary for the month
  workingDays: {
    total: { type: Number, default: 22 },
    present: { type: Number, default: 0 },
    absent: { type: Number, default: 0 },
    leaves: { type: Number, default: 0 },
    holidays: { type: Number, default: 0 }
  },

  // Calculated amounts
  grossEarnings: {
    type: Number,
    default: 0
  },
  totalDeductions: {
    type: Number,
    default: 0
  },
  netSalary: {
    type: Number,
    default: 0
  },

  // Payment details
  paymentStatus: {
    type: String,
    enum: ['pending', 'processed', 'paid', 'on-hold'],
    default: 'pending'
  },
  paymentDate: {
    type: Date
  },
  paymentMethod: {
    type: String,
    enum: ['bank-transfer', 'cheque', 'cash'],
    default: 'bank-transfer'
  },
  transactionId: {
    type: String,
    default: ''
  },

  // Remarks
  remarks: {
    type: String,
    default: ''
  },

  // Generated by
  generatedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  approvedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  }

}, {
  timestamps: true
});

// Compound index for unique payroll per employee per month
payrollSchema.index({ employee: 1, month: 1, year: 1 }, { unique: true });
payrollSchema.index({ paymentStatus: 1 });
payrollSchema.index({ year: 1, month: 1 });

// Pre-save middleware to calculate totals
payrollSchema.pre('save', function(next) {
  // Calculate gross earnings
  const earnings = this.earnings;
  this.grossEarnings = 
    earnings.basic + 
    earnings.hra + 
    earnings.conveyance + 
    earnings.medical + 
    earnings.specialAllowance + 
    earnings.bonus + 
    earnings.overtime + 
    earnings.other;

  // Calculate total deductions
  const deductions = this.deductions;
  this.totalDeductions = 
    deductions.providentFund + 
    deductions.professionalTax + 
    deductions.incomeTax + 
    deductions.insurance + 
    deductions.loanRepayment + 
    deductions.other;

  // Calculate net salary
  this.netSalary = this.grossEarnings - this.totalDeductions;

  next();
});

// Static method to generate payroll for all employees
payrollSchema.statics.generateMonthlyPayroll = async function(month, year, generatedBy) {
  const Employee = require('./Employee');
  const Attendance = require('./Attendance');

  const employees = await Employee.find({ status: 'active' });
  const payrolls = [];

  for (const employee of employees) {
    // Get attendance summary
    const startDate = new Date(year, month - 1, 1);
    const endDate = new Date(year, month, 0);
    
    const attendanceSummary = await Attendance.getEmployeeSummary(
      employee._id, 
      startDate, 
      endDate
    );

    // Calculate earnings based on employee salary structure
    const earnings = {
      basic: employee.salary.basic,
      hra: Math.round(employee.salary.basic * 0.4), // 40% of basic
      conveyance: 1600,
      medical: 1250,
      specialAllowance: employee.salary.allowances,
      bonus: 0,
      overtime: 0,
      other: 0
    };

    // Calculate deductions
    const grossForPF = earnings.basic + earnings.hra;
    const deductions = {
      providentFund: Math.round(grossForPF * 0.12), // 12% PF
      professionalTax: 200,
      incomeTax: Math.round(employee.salary.basic * 0.1), // Simplified
      insurance: 500,
      loanRepayment: 0,
      other: employee.salary.deductions
    };

    const payroll = {
      employee: employee._id,
      month,
      year,
      earnings,
      deductions,
      workingDays: {
        total: 22,
        present: attendanceSummary.present,
        absent: attendanceSummary.absent,
        leaves: attendanceSummary.leave,
        holidays: 0
      },
      generatedBy
    };

    payrolls.push(payroll);
  }

  // Use insertMany with ordered: false to continue on duplicates
  try {
    const result = await this.insertMany(payrolls, { ordered: false });
    return result;
  } catch (error) {
    if (error.code === 11000) {
      // Duplicate key error - some payrolls already exist
      return error.insertedDocs || [];
    }
    throw error;
  }
};

const Payroll = mongoose.model('Payroll', payrollSchema);
module.exports = Payroll;
